#!/bin/bash

helpmessage() {
   echo -e "usage: fb [branches...]\n"
   echo -e "   -h, --help     show (this) help message"
   echo -e "   -o, --out      output directory"
}

function run_configs {
   branch=$1
   output=$(readlink -f $2)

   cmdlog=$output/cmd.log

   # checkout branch
   echo -e "  checking out branch: \033[34m$branch\033[0m"
   git checkout $branch &> $cmdlog

   pushd HeavyIonsAnalysis/JetAnalysis/python/jets/ >> $cmdlog

   # regenerate jet sequences
   rm ak*JetSequence_*_*_cff.py*
   ./makeJetSequences.sh

   popd >> $cmdlog

   # clean and rebuild
   # scram b distclean
   scram b -j4 &> $output/build.log

   mkdir test_configs_${branch}
   cp HeavyIonsAnalysis/JetAnalysis/test/runForestAOD_*.py test_configs_${branch}

   # run all foresting configs
   echo -e "   running configs..."
   pushd test_configs_${branch} >> $cmdlog

   configs=(runForestAOD_*.py)
   children=()

   for config in ${configs[@]}; do
      # run all events for validation
      sed -i 's/input = cms.untracked.int32(1)/input = cms.untracked.int32(-1)/' $config
      sed -i "s/HiForestAOD.root/HiForestAOD_${config%.*}.root/g" $config

      cmsRun $config &> ${config%.*}.log &
      children+=("$!")
   done

   for c in "${!children[@]}"; do
      config=${configs[$c]}

      wait ${children[$c]}
      retc=$?

      echo -n '    '
      [ $retc -eq 0 ] && echo -ne "\033[32mDONE:" || echo -ne "\033[31mFAIL:"
      echo -e " $config\033[0m"
   done

   echo

   mv HiForestAOD_*.root $output
   mv runForestAOD_*.log $output

   popd >> $cmdlog

   # cleanup
   rm -r test_configs_${branch}
}

ARGS=()

while [ $# -gt 0 ]; do
   case "$1" in
      -h|--help)     helpmessage; exit 0 ;;
      -o|--out)      out="$2"; shift 2 ;;
      --out=*)       out="${1#*=}"; shift ;;
      -*|--*)        echo -e "invalid option: $1\n"; exit 1 ;;
      *)             ARGS+=("$1"); shift ;;
   esac
done

set -- "${ARGS[@]}"
echo

branches=( "$@" )
[ $out ] &&
   outdir=$(readlink -f $out) ||
   outdir=$(pwd)/fb-output/
outdir=$outdir/forests

# check cms environment
if [[ -z $CMSSW_BASE || $(pwd)/ != $CMSSW_BASE/* ]]; then
   echo -e "current directory: $pwd does not match cmsenv: $CMSSW_BASE\n"
   exit 1
fi

pushd $CMSSW_BASE/src/ > /dev/null

# check for uncommitted changes
if ! git diff-index --quiet HEAD; then
   echo -e "there are uncommitted changes\n"
   exit 1
fi

# produce forest files
for branch in ${branches[@]}; do
   mkdir -p $outdir/$branch/
   run_configs $branch $outdir/$branch/
done

popd > /dev/null

echo -e "  done!\n"
