#!/bin/bash

helpmessage() {
   echo -e "usage: ./till.sh [skip]\n"
   echo -e "   -c, --config   cmsrun config"
   echo -e "   -f, --forward  forward arguments to grow"
   echo -e "   -g, --grow     grow trees directly"
   echo -e "   -h, --help     show (this) help message"
   echo -e "   -l, --logs     logs directory"
   echo -e "   -n             number of files"
   echo -e "   -o, --output   output directory"
   echo -e "   -r, --runs     print run numbers"
   echo -e "   -s, --stream   data streamer"
}

ARGS=()

while [ $# -gt 0 ]; do
   case "$1" in
      -c|--config)   config="$2"; shift 2 ;;
      --config=*)    config="${1#*=}"; shift ;;
      -f|--forward)  fwargs="$2"; shift 2 ;;
      --forward=*)   fwargs="${1#*=}"; shift ;;
      -g|--grow)     grow=1; shift ;;
      -h|--help)     helpmessage; exit 0 ;;
      -l|--logs)     log="$2"; shift 2 ;;
      --logs=*)      out="${1#*=}"; shift ;;
      -n)            n="$2"; shift 2 ;;
      -n=*)          n="${1#*=}"; shift ;;
      -o|--output)   out="$2"; shift 2 ;;
      --output=*)    out="${1#*=}"; shift ;;
      -r|--runs)     recho=1; shift ;;
      -s|--stream)   stream="$2"; shift 2 ;;
      --stream=*)    stream="${1#*=}"; shift ;;
      -*)            echo -e "invalid option: $1\n"; exit 1 ;;
      *)             ARGS+=("$1"); shift ;;
   esac
done

set -- "${ARGS[@]}"

[ $# -gt 1 ] && { echo -e "check arguments\n"; exit 1; }
[ $grow ] && [ ! $config ] && {
   echo -e "no config specified for --grow\n"; exit 1; }

skip=$1

[ $out ] &&
   outdir=$(readlink -f $out) ||
   outdir=/eos/cms/store/group/phys_heavyions/rbi/farm/
[ $log ] &&
   logdir=$(readlink -f $log) ||
   logdir=/afs/cern.ch/work/r/rbi/private/logs/farm/
[ $stream ] || stream=HIPhysicsMinimumBiasReducedFormat8

data=/eos/cms/store/t0streamer/Data/$stream/000

[ $n ] || n=4

runs=()

for high in $(ls $data); do
   for low in $(ls $data/$high); do
      run=$high$low

      [ $skip ] && grep -Fqx "$run" $skip ||
         runs+=("$run")
   done
done

[ $recho ] && { printf '%s\n' "${runs[@]}"; exit 0; }

for run in ${runs[@]}; do
   mkdir -p $logdir/$run/
   list=$logdir/$run/till_${stream}_$run.list

   files=($data/$high/$low/*)
   nfiles=${#files[@]}; nf=$n
   [ $nfiles -lt $nf ] && nf=$nfiles
   indices=($(shuf -i 1-$nfiles -n $nf))
   for i in "${indices[@]}"; do
      echo "file:${files[$((i-1))]}" >> $list
   done

   if [ ! $grow ]; then
      echo "./grow $fwargs $list $config -l $logdir/$run -o $outdir/$run"
   else
      echo -e "  prepared: \033[34m$list\033[0m"
      grow $fwargs -l $logdir/$run/ -o $outdir/$run/ $list $config
   fi
done
